Name: Osama Sidahmed

Date: 07 Nov 2021

### Description

Source of data is [here](https://ai.stanford.edu/~jkrause/cars/car_dataset.html).

**Overview**

       The Cars dataset or Car196, contains 16,185 images of 196 classes of cars. The data is split into 8,144 training images and 8,041 testing images, where each class has been split roughly in a 50-50 split. Classes are typically at the level of Make, Model, Year, e.g. 2012 Tesla Model S or 2012 BMW M3 coupe.


**Acknowledgements**

Data source and banner image: http://ai.stanford.edu/~jkrause/cars/car_dataset.html contains all bounding boxes and labels for both training and tests.\
If you use this dataset, please cite the following paper:\
3D Object Representations for Fine-Grained Categorization\
Jonathan Krause, Michael Stark, Jia Deng, Li Fei-Fei\
4th IEEE Workshop on 3D Representation and Recognition, at ICCV 2013 (3dRR-13). Sydney, Australia. Dec. 8, 2013.

### Objective

The main objective of this project is develop a CNN algorithm that differentiates between the different 196 classes using employing Tensorflow and using the standford cars 196 dataset. Some examples of the classes are:

        'Audi TT Hatchback 2011', 
        'Audi S6 Sedan 2011'
        'Audi S5 Convertible 2012', 
        'Audi S5 Coupe 2012'
        'Audi TT RS Coupe 2012', 
        'BMW ActiveHybrid 5 Sedan 2012'
        'BMW 6 Series Convertible 2007', 
        'BMW X5 SUV 2007'
        
The class description is a combination of the make, model and the year.

### Exploratory Data Analysis and Preparation

On this section we will try to better understand the data and spot some clear patterns.

In [378]:
# Load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

It has been noticed that the file containing the data classification is provided in a .mat file that we need to process to be able to read the data stored in it. 

In [379]:
# import loadmat from scipy to read the .mat file
from scipy.io import loadmat

In [380]:
# load the .mat files
mat_train = loadmat('data/cars_train_annos.mat', squeeze_me=True)
mat_test = loadmat('data/cars_test_annos_withlabels.mat', squeeze_me=True)
mat_meta = loadmat('data/cars_meta.mat', squeeze_me=True)

In [381]:
# what is the type of the output?
type(mat_train)

dict

The outcome is a dictionary, we can extract the data from the dictionary.

In [382]:
# display the output
mat_train

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sat Dec 14 14:13:07 2013',
 '__version__': '1.0',
 '__globals__': [],
 'annotations': array([(39, 116, 569, 375, 14, '00001.jpg'),
        (36, 116, 868, 587, 3, '00002.jpg'),
        (85, 109, 601, 381, 91, '00003.jpg'), ...,
        (26, 246, 660, 449, 163, '08142.jpg'),
        (78, 526, 1489, 908, 112, '08143.jpg'),
        (20, 240, 862, 677, 17, '08144.jpg')],
       dtype=[('bbox_x1', 'O'), ('bbox_y1', 'O'), ('bbox_x2', 'O'), ('bbox_y2', 'O'), ('class', 'O'), ('fname', 'O')])}

In [383]:
# display the output
mat_test

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sat Dec 14 14:13:07 2013',
 '__version__': '1.0',
 '__globals__': [],
 'annotations': array([(30, 52, 246, 147, 181, '00001.jpg'),
        (100, 19, 576, 203, 103, '00002.jpg'),
        (51, 105, 968, 659, 145, '00003.jpg'), ...,
        (33, 27, 602, 252, 17, '08039.jpg'),
        (33, 142, 521, 376, 38, '08040.jpg'),
        (77, 73, 506, 380, 32, '08041.jpg')],
       dtype=[('bbox_x1', 'O'), ('bbox_y1', 'O'), ('bbox_x2', 'O'), ('bbox_y2', 'O'), ('class', 'O'), ('fname', 'O')])}

In [384]:
# display the output
mat_meta

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sat Dec 14 14:13:07 2013',
 '__version__': '1.0',
 '__globals__': [],
 'class_names': array(['AM General Hummer SUV 2000', 'Acura RL Sedan 2012',
        'Acura TL Sedan 2012', 'Acura TL Type-S 2008',
        'Acura TSX Sedan 2012', 'Acura Integra Type R 2001',
        'Acura ZDX Hatchback 2012',
        'Aston Martin V8 Vantage Convertible 2012',
        'Aston Martin V8 Vantage Coupe 2012',
        'Aston Martin Virage Convertible 2012',
        'Aston Martin Virage Coupe 2012', 'Audi RS 4 Convertible 2008',
        'Audi A5 Coupe 2012', 'Audi TTS Coupe 2012', 'Audi R8 Coupe 2012',
        'Audi V8 Sedan 1994', 'Audi 100 Sedan 1994', 'Audi 100 Wagon 1994',
        'Audi TT Hatchback 2011', 'Audi S6 Sedan 2011',
        'Audi S5 Convertible 2012', 'Audi S5 Coupe 2012',
        'Audi S4 Sedan 2012', 'Audi S4 Sedan 2007',
        'Audi TT RS Coupe 2012', 'BMW ActiveHybrid 5 Sedan 2012',
        'BMW 1 Series Convertibl

We are only interested in the 'annotations' and the 'class_names' values.

In [385]:
# explore the dictionary
mat_train['annotations']

array([(39, 116, 569, 375, 14, '00001.jpg'),
       (36, 116, 868, 587, 3, '00002.jpg'),
       (85, 109, 601, 381, 91, '00003.jpg'), ...,
       (26, 246, 660, 449, 163, '08142.jpg'),
       (78, 526, 1489, 908, 112, '08143.jpg'),
       (20, 240, 862, 677, 17, '08144.jpg')],
      dtype=[('bbox_x1', 'O'), ('bbox_y1', 'O'), ('bbox_x2', 'O'), ('bbox_y2', 'O'), ('class', 'O'), ('fname', 'O')])

In [386]:
# explore the dictionary
mat_meta['class_names']

array(['AM General Hummer SUV 2000', 'Acura RL Sedan 2012',
       'Acura TL Sedan 2012', 'Acura TL Type-S 2008',
       'Acura TSX Sedan 2012', 'Acura Integra Type R 2001',
       'Acura ZDX Hatchback 2012',
       'Aston Martin V8 Vantage Convertible 2012',
       'Aston Martin V8 Vantage Coupe 2012',
       'Aston Martin Virage Convertible 2012',
       'Aston Martin Virage Coupe 2012', 'Audi RS 4 Convertible 2008',
       'Audi A5 Coupe 2012', 'Audi TTS Coupe 2012', 'Audi R8 Coupe 2012',
       'Audi V8 Sedan 1994', 'Audi 100 Sedan 1994', 'Audi 100 Wagon 1994',
       'Audi TT Hatchback 2011', 'Audi S6 Sedan 2011',
       'Audi S5 Convertible 2012', 'Audi S5 Coupe 2012',
       'Audi S4 Sedan 2012', 'Audi S4 Sedan 2007',
       'Audi TT RS Coupe 2012', 'BMW ActiveHybrid 5 Sedan 2012',
       'BMW 1 Series Convertible 2012', 'BMW 1 Series Coupe 2012',
       'BMW 3 Series Sedan 2012', 'BMW 3 Series Wagon 2012',
       'BMW 6 Series Convertible 2007', 'BMW X5 SUV 2007',
       'BMW X

In [387]:
# explore the dictionary, an example
mat_meta['class_names'][92]

'Dodge Challenger SRT8 2011'

In [388]:
# This is how to extract the datatypes to use as dataframes header
mat_train['annotations'].dtype.descr[0][0]

'bbox_x1'

In [389]:
# extract the data from the .mat files and store them in thre (3) separate datframes

df_1_header = list()

    
# extract the dscription ('relative_im_path', 'O') and store that in a list as header
df_1_header = [x[0] for x in mat_train['annotations'].dtype.descr]

# and extract the values ('car_ims/000001.jpg', 112, 7, 853, 717, 1, 0) and store that in lists representing the columns
df_1_values_0 = [x[0] for x in mat_train['annotations']]
df_1_values_1 = [x[1] for x in mat_train['annotations']]
df_1_values_2 = [x[2] for x in mat_train['annotations']]
df_1_values_3 = [x[3] for x in mat_train['annotations']]
df_1_values_4 = [x[4] for x in mat_train['annotations']]
df_1_values_5 = [x[5] for x in mat_train['annotations']]

# create a dataframe
df_train_bounding_box = pd.DataFrame(list(zip(df_1_values_0, df_1_values_1,
                                       df_1_values_2,df_1_values_3,
                                       df_1_values_4,df_1_values_5)), columns = df_1_header)

# do the same for the test data
# and extract the values ('car_ims/000001.jpg', 112, 7, 853, 717, 1, 0) and store that in lists representing the columns
df_1_values_0 = [x[0] for x in mat_test['annotations']]
df_1_values_1 = [x[1] for x in mat_test['annotations']]
df_1_values_2 = [x[2] for x in mat_test['annotations']]
df_1_values_3 = [x[3] for x in mat_test['annotations']]
df_1_values_4 = [x[4] for x in mat_test['annotations']]
df_1_values_5 = [x[5] for x in mat_test['annotations']]

# create a dataframe
df_test_bounding_box = pd.DataFrame(list(zip(df_1_values_0, df_1_values_1,
                                       df_1_values_2,df_1_values_3,
                                       df_1_values_4,df_1_values_5)), columns = df_1_header)


# store the class (196 classes) on separate dataframe
classes = np.arange(1,len(mat_meta['class_names'])+1)
df_classes = pd.DataFrame(list(zip(classes, mat_meta['class_names'])), columns = ['class', 'name'])

In [390]:
df_train_bounding_box

bbox_x1  bbox_y1  bbox_x2  bbox_y2  class      fname
0          39      116      569      375     14  00001.jpg
1          36      116      868      587      3  00002.jpg
2          85      109      601      381     91  00003.jpg
3         621      393     1484     1096    134  00004.jpg
4          14       36      133       99    106  00005.jpg
...       ...      ...      ...      ...    ...        ...
8139        3       44      423      336     78  08140.jpg
8140      138      150      706      523    196  08141.jpg
8141       26      246      660      449    163  08142.jpg
8142       78      526     1489      908    112  08143.jpg
8143       20      240      862      677     17  08144.jpg

[8144 rows x 6 columns]

In [391]:
df_test_bounding_box

bbox_x1  bbox_y1  bbox_x2  bbox_y2  class      fname
0          30       52      246      147    181  00001.jpg
1         100       19      576      203    103  00002.jpg
2          51      105      968      659    145  00003.jpg
3          67       84      581      407    187  00004.jpg
4         140      151      593      339    185  00005.jpg
...       ...      ...      ...      ...    ...        ...
8036       49       57     1169      669     63  08037.jpg
8037       23       18      640      459     16  08038.jpg
8038       33       27      602      252     17  08039.jpg
8039       33      142      521      376     38  08040.jpg
8040       77       73      506      380     32  08041.jpg

[8041 rows x 6 columns]

Let us look at this dataframe columns:
- **fname:** the image file name.
- **bbox_x1, bbox_y1, bbox_x2, and bbox_y2:** define each image's object of interest bounding box. We may or may not use this information
- **class:** the image class, one of 196 possible classes as defined by the next dataframe

In [392]:
df_classes

class                              name
0        1        AM General Hummer SUV 2000
1        2               Acura RL Sedan 2012
2        3               Acura TL Sedan 2012
3        4              Acura TL Type-S 2008
4        5              Acura TSX Sedan 2012
..     ...                               ...
191    192  Volkswagen Beetle Hatchback 2012
192    193          Volvo C30 Hatchback 2012
193    194              Volvo 240 Sedan 1993
194    195               Volvo XC90 SUV 2007
195    196     smart fortwo Convertible 2012

[196 rows x 2 columns]

Let us look at this dataframe columns:
- **class:** the image class
- **name:** the class name

For the sake of convenience, let us merge these two dataframes together. 

In [393]:
df_train_info = df_train_bounding_box.merge(df_classes, left_on='class', right_on='class')
df_train_info.sample(5)

bbox_x1  bbox_y1  bbox_x2  bbox_y2  class      fname  \
1973       15       36      271      154     44  00749.jpg   
7707       52       96      754      498     98  01434.jpg   
3931        1       32      767      688    171  03301.jpg   
4382       18       92      532      297    174  00766.jpg   
6460       49       93      225      169    151  04983.jpg   

                                            name  
1973  Bentley Continental Flying Spur Sedan 2007  
7707                  Eagle Talon Hatchback 1998  
3931                     Nissan 240SX Coupe 1998  
4382              Ram C/V Cargo Van Minivan 2012  
6460            Lamborghini Aventador Coupe 2012

In [394]:
# do the same for the test data
df_test_info = df_test_bounding_box.merge(df_classes, left_on='class', right_on='class')
df_test_info.sample(5)

bbox_x1  bbox_y1  bbox_x2  bbox_y2  class      fname  \
2101       66      123      664      356    130  04828.jpg   
7499       24       12      569      458    131  04808.jpg   
4308        1       66      350      204     53  02018.jpg   
5149        1       22      315      200    110  07755.jpg   
7271       66       46      439      277     54  07591.jpg   

                                               name  
2101                Hyundai Veloster Hatchback 2012  
7499                      Hyundai Santa Fe SUV 2012  
4308            Cadillac Escalade EXT Crew Cab 2007  
5149                             Ford Edge SUV 2012  
7271  Chevrolet Silverado 1500 Hybrid Crew Cab 2012

Let us check the number of train vs the number of test images.

In [395]:
df_train_info.shape[0], df_test_info.shape[0]

(8144, 8041)

We have almost a 50/50 split of images, can we increase the to the favor of train set? we will do that later if necessary after we do more EDA.

Let us now have a look some sample images of our different classes, but first let us first load our data using the`ImageDataGenerator`.

Before we use the ImageDataGenerator, we need to re-organize the data into folders where each class is stored in a separate folder. The best and fastest method to do this is using the command line.

The current setup is 8144 in one folder (train data folder) and 8041 in another folder (test data folder).

The end result is two folders, one for train data images and another one for test data images where each folder contain 196 folders, one folder for each class.

Now to decide if we want to reassign some of the test data to the train data to have a split of ~70/30 instead of the ~50/50, let us have a quick look at the train and test data in the dataframe.

In [396]:
for class_ in df_train_info['class'].unique():
    print(f' Class ***{class_ }*** \n train:{df_train_info["class"][df_train_info["class"] == class_].count()}, test:{df_test_info["class"][df_train_info["class"] == class_].count()}')

 Class ***14*** 
 train:43, test:43
 Class ***3*** 
 train:43, test:43
 Class ***91*** 
 train:39, test:39
 Class ***134*** 
 train:34, test:34
 Class ***106*** 
 train:42, test:42
 Class ***123*** 
 train:45, test:45
 Class ***89*** 
 train:44, test:44
 Class ***96*** 
 train:41, test:41
 Class ***167*** 
 train:48, test:48
 Class ***58*** 
 train:44, test:44
 Class ***49*** 
 train:38, test:38
 Class ***186*** 
 train:39, test:39
 Class ***135*** 
 train:42, test:42
 Class ***85*** 
 train:44, test:44
 Class ***193*** 
 train:42, test:42
 Class ***172*** 
 train:44, test:44
 Class ***73*** 
 train:45, test:45
 Class ***192*** 
 train:43, test:43
 Class ***57*** 
 train:38, test:38
 Class ***79*** 
 train:49, test:49
 Class ***36*** 
 train:41, test:41
 Class ***120*** 
 train:43, test:43
 Class ***170*** 
 train:44, test:44
 Class ***194*** 
 train:46, test:46
 Class ***184*** 
 train:41, test:41
 Class ***86*** 
 train:43, test:43
 Class ***180*** 
 train:43, test:43
 Class ***154**

The classes are distributed almost evenly between the train and test sets.

To change this balance to ~70/30 we need to reassign around 3200 images from test to train which is around 3150/196 = 16 images per class.

To do that in command line we first need to:
1. rename the images in the test dataframe to continue in order after the train images names
2. merge the two dateframes while introducing a new column to represent if the image is a train or test (0 or 1)
3. reassign the images in the dataframe (16 of each class)
4. export a text file with the images the train/test value and the class
5. use command line to:
    1. rename all the test images respectively based on the step 1 above
    2. create the respective folders train-> 196 subfolders and test-> 196 subfolders
    3. copy the images to the right folder based on the text file

In [397]:
# 1. rename the images in the test dataframe to continue in order after the train images names
# what is the name of the last image in the train dataframe?
df_train_info['fname'].tail()
# 08140.jpg

df_test_info['fname'] = df_test_info.apply(lambda x: ('0' + (df_test_info['fname'].str.replace('.jpg', '').astype(int) + 8140).astype(str) + '.jpg'))

<ipython-input-397-fed5d1218c01>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  df_test_info['fname'] = df_test_info.apply(lambda x: ('0' + (df_test_info['fname'].str.replace('.jpg', '').astype(int) + 8140).astype(str) + '.jpg'))


In [398]:
df_test_info

bbox_x1  bbox_y1  bbox_x2  bbox_y2  class       fname  \
0          30       52      246      147    181   08141.jpg   
1          84      169      561      443    181   08195.jpg   
2          12       31      489      226    181   08463.jpg   
3           7      121      635      357    181   08680.jpg   
4           9       42      282      207    181   08681.jpg   
...       ...      ...      ...      ...    ...         ...   
8036       23       73      430      278     77  014604.jpg   
8037       36      218      522      467     77  014624.jpg   
8038       24       63      336      235     77  015186.jpg   
8039       19       30      417      194     77  015736.jpg   
8040       72      153      474      344     77  015784.jpg   

                                   name  
0               Suzuki Aerio Sedan 2007  
1               Suzuki Aerio Sedan 2007  
2               Suzuki Aerio Sedan 2007  
3               Suzuki Aerio Sedan 2007  
4               Suzuki Aerio Sedan 2007  
...                                 ...  
8036  Chrysler Sebring Convertible 2010  
8037  Chrysler Sebring Convertible 2010  
8038  Chrysler Sebring Convertible 2010  
8039  Chrysler Sebring Convertible 2010  
8040  Chrysler Sebring Convertible 2010  

[8041 rows x 7 columns]

Now images file names are a continuation from the train dataframe.

In [399]:
# df_test_info.iloc[:10,:].copy()

We can now merge the two dattaframes together butt before the we need to create a new column 'test' equals to 0 for the train images and 1 for the test images.

In [400]:
# 2. merge the two dateframes while introducing a new column to represent if the image is a train or test (0 or 1)
df_train_info['test'] = '0'
df_test_info['test'] = '1'

df_info = pd.concat([df_train_info,df_test_info],ignore_index=True)

In [401]:
df_info

bbox_x1  bbox_y1  bbox_x2  bbox_y2  class       fname  \
0           39      116      569      375     14   00001.jpg   
1           39       52      233      150     14   00017.jpg   
2           52       47      586      260     14   00411.jpg   
3           47       92      209      178     14   00467.jpg   
4            7       51      253      156     14   00888.jpg   
...        ...      ...      ...      ...    ...         ...   
16180       23       73      430      278     77  014604.jpg   
16181       36      218      522      467     77  014624.jpg   
16182       24       63      336      235     77  015186.jpg   
16183       19       30      417      194     77  015736.jpg   
16184       72      153      474      344     77  015784.jpg   

                                    name test  
0                    Audi TTS Coupe 2012    0  
1                    Audi TTS Coupe 2012    0  
2                    Audi TTS Coupe 2012    0  
3                    Audi TTS Coupe 2012    0  
4                    Audi TTS Coupe 2012    0  
...                                  ...  ...  
16180  Chrysler Sebring Convertible 2010    1  
16181  Chrysler Sebring Convertible 2010    1  
16182  Chrysler Sebring Convertible 2010    1  
16183  Chrysler Sebring Convertible 2010    1  
16184  Chrysler Sebring Convertible 2010    1  

[16185 rows x 8 columns]

In [623]:
df_info.sample(3)

bbox_x1  bbox_y1  bbox_x2  bbox_y2  class       fname  \
6329        42        8      465      280    100   01525.jpg   
11577       26       14      235      179    143  015058.jpg   
15248       51      121      458      290     62  016091.jpg   

                                  name test  
6329         FIAT 500 Convertible 2012    0  
11577          Isuzu Ascender SUV 2008    1  
15248  Chevrolet Tahoe Hybrid SUV 2012    1

In [624]:
# 3. reassign the images in the dataframe (16 of each class)
# this step requires us changing the test column value from 1 to 0 for these images

for class_ in df_info['class'].unique():
    # get the indexes of rows to change thier test values
    df = df_info['test'][(df_info['class'] == class_) & (df_info['test'] == '1')].iloc[:16]
    # use the above as a mask to change the test values
    df_info['test'][df.index] = '0'

<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['test'][df.index] = '0'
<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['test'][df.index] = '0'
<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['test'][df.index] = '0'
<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a cop

<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['test'][df.index] = '0'
<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['test'][df.index] = '0'
<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['test'][df.index] = '0'
<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a cop

<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['test'][df.index] = '0'
<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['test'][df.index] = '0'
<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['test'][df.index] = '0'
<ipython-input-624-96b6c70019f7>:6: SettingWithCopyWarning: 
A value is trying to be set on a cop

Now let us check he new value_counts(), we are expecting a 70/30 split instead of the 50/50 we had earlier.

In [625]:
df_info['test'].value_counts()

0    11280
1     4905
Name: test, dtype: int64

Good, Let us confirm that.

In [626]:
df_info['test'].value_counts()[0] / (df_info['test'].value_counts()[0]+ df_info['test'].value_counts()[1])

0.6969416126042632

Perfect, around 70/30 split.

In [647]:
for class_ in df_info['class'].unique():
    print(f' Class ***{class_ }*** \n train:{df_info["test"][df_info["class"] == class_].value_counts()[0]}, test:{df_info["test"][df_info["class"] == class_].value_counts()[1]}')

 Class ***14*** 
 train:59, test:26
 Class ***3*** 
 train:59, test:27
 Class ***91*** 
 train:55, test:22
 Class ***134*** 
 train:50, test:17
 Class ***106*** 
 train:58, test:25
 Class ***123*** 
 train:61, test:28
 Class ***89*** 
 train:60, test:28
 Class ***96*** 
 train:57, test:25
 Class ***167*** 
 train:64, test:31
 Class ***58*** 
 train:60, test:28
 Class ***49*** 
 train:54, test:21
 Class ***186*** 
 train:55, test:22
 Class ***135*** 
 train:58, test:26
 Class ***85*** 
 train:60, test:27
 Class ***193*** 
 train:58, test:25
 Class ***172*** 
 train:60, test:28
 Class ***73*** 
 train:61, test:28
 Class ***192*** 
 train:59, test:26
 Class ***57*** 
 train:54, test:21
 Class ***79*** 
 train:65, test:32
 Class ***36*** 
 train:57, test:25
 Class ***120*** 
 train:59, test:26
 Class ***170*** 
 train:60, test:28
 Class ***194*** 
 train:62, test:29
 Class ***184*** 
 train:57, test:24
 Class ***86*** 
 train:59, test:26
 Class ***180*** 
 train:59, test:26
 Class ***154**

In [628]:
df_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16185 entries, 0 to 16184
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   bbox_x1  16185 non-null  int64 
 1   bbox_y1  16185 non-null  int64 
 2   bbox_x2  16185 non-null  int64 
 3   bbox_y2  16185 non-null  int64 
 4   class    16185 non-null  int64 
 5   fname    16185 non-null  object
 6   name     16185 non-null  object
 7   test     16185 non-null  object
dtypes: int64(5), object(3)
memory usage: 1011.7+ KB


Let us change the `test` data type to integer.

In [635]:
df_info['test'] = df_info['test'].astype(int) 

In [636]:
df_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16185 entries, 0 to 16184
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   bbox_x1  16185 non-null  int64 
 1   bbox_y1  16185 non-null  int64 
 2   bbox_x2  16185 non-null  int64 
 3   bbox_y2  16185 non-null  int64 
 4   class    16185 non-null  int64 
 5   fname    16185 non-null  object
 6   name     16185 non-null  object
 7   test     16185 non-null  int32 
dtypes: int32(1), int64(5), object(2)
memory usage: 948.5+ KB


In [651]:
# 4. export a text file with the images the train/test value and the class
df_info[['fname', 'class', 'test']].to_csv('data/df_info.csv', sep=';', encoding='utf-8-sig', header=True, index = False)

#5. use command line to: \
A. rename all the test images respectively based on the step 1 above

    
    file_name=8145; 
    for i in *.jpg; 
    do 
    new=$(printf "%05d.jpg" "$file_name"); 
    mv -i -- "$i" "$new"; 
    let file_name=file_name+1; 
    done

    
B. create the respective folders train-> 196 subfolders and test-> 196 subfolders


    mkdir train test
    
    for i in {1..196}; 
    do 
    mkdir "train/$i";
mkdir "test/$i"; 
    done
    
C. copy the newly renamed files to the directory where the train set files are

    mv  -v test/* train/

D. copy the images to the right folder based on the text file 
    
    while IFS=";" read fname class test; 
    do 
    if [ "$test" == "0" ]; then  
    echo "Moving file: $fname class: $class to folder: train/$class"; 
    mv "$fname" "../directory/train/$class/"; 
    elif [ "$test" == "1" ]; then 
    echo "Moving file: $fname class: $class to folder: test/$class"; 
    mv "$fname" "../directory/test/$class/"; 
    fi; 
    done < "df_info.csv"

In [131]:
# import th ImageDataGenerator
from tensorflow.keras.preprocessing.image import ImageDataGenerator

The generator will help us to augment our data when it comes to creating a more robust model by performing image transformations on our training set, mainly:
- reflect
- rotate
- crop and zoom
- shear, and others

In [140]:
# the dimension of images to be processed
height = 224 
height = 224
channels = 3

# create the generator for the trainig set
train_idg = ImageDataGenerator(rescale = 1./255, rotation_range = 30,
                              shear_range = 0.2, zoom_range = 0.2,
                              horizontal_flip = True)

# define the directory
train_gen = train_idg.flow_from_directory('data', target_size = (height, height),
                                         color_mode = 'rgb', batch_size = 32,
                                         class_mode = 'categorical') 

Found 16185 images belonging to 3 classes.


### Modelling and Evaluation